# syntax=docker/dockerfile:1

# There is no build step: templates are rendered at request time and the
# responsive images are generated by tools/build-images.mjs and committed. So a
# single stage with production dependencies is the whole image.
FROM node:22-alpine AS runtime

# dumb-init gives PID 1 proper signal handling, so `docker stop` shuts the
# server down cleanly instead of waiting out the 10s SIGKILL timeout.
RUN apk add --no-cache dumb-init

ENV NODE_ENV=production \
    PORT=3000 \
    HOST=0.0.0.0

WORKDIR /app

# Dependencies first: this layer only rebuilds when the lockfile changes, so
# ordinary content edits reuse the cache.
COPY package.json package-lock.json ./
RUN npm ci --omit=dev && npm cache clean --force

COPY server ./server
COPY views ./views
COPY content ./content
COPY public ./public
# The avatar model lives here. app.js registers `assets` as a static root, so
# omitting it made every /assets/* URL 404 inside the container while working
# fine in local dev, where the directory is simply present on disk.
COPY assets ./assets
COPY images ./images
COPY logos ./logos
COPY docs ./docs
COPY audio ./audio
COPY favicon.ico ./favicon.ico

# node:alpine ships an unprivileged `node` user. Nothing here needs to write to
# disk, so the filesystem can also be mounted read-only in compose.
USER node

EXPOSE 3000

# Uses the app's own readiness endpoint rather than a bare TCP check, so a
# process that is up but has failed to load content is still reported unhealthy.
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
  CMD node -e "fetch('http://127.0.0.1:3000/healthz').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"

ENTRYPOINT ["dumb-init", "--"]
CMD ["node", "server/app.js"]
